#!/bin/sh
#
# Start the 433ctrl service.
#
### BEGIN INIT INFO
# Provides:          openhab
# Required-Start:    $local_fs $syslog $crtl433
# Required-Stop:     $local_fs $syslog $ctrl433
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: openhab
# Description:       openhab
### END INIT INFO

dir=/opt/openhab
name=openhab
exe=$dir/start_daemon.sh
pid=/var/run/$name.pid

. /lib/lsb/init-functions

case "$1" in
    start)
	log_begin_msg "Starting $name service"
	start-stop-daemon --start --quiet --pidfile $pid --exec $exe >/dev/null
	log_end_msg $?
	;;
    stop)
	log_begin_msg "Stopping $name service"
	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $pid
	log_end_msg $?
	;;
    *)
	echo "$0 {start|stop}"
	;;
esac
